export enum Path {
  ManagerAssist = '/managerAssist',
  Home = `${Path.ManagerAssist}/home`,
  HomeDashboard = `${Path.ManagerAssist}/home/dashboard`,
  Thread = `${Path.ManagerAssist}/home/[id]`,
  Modeling = `${Path.ManagerAssist}/modeling`,
  Onboarding = `${Path.ManagerAssist}/setup`,
  OnboardingConnection = `${Path.ManagerAssist}/setup/connection`,
  OnboardingModels = `${Path.ManagerAssist}/setup/models`,
  OnboardingRelationships = `${Path.ManagerAssist}/setup/relationships`,
  Knowledge = `${Path.ManagerAssist}/knowledge`,
  KnowledgeQuestionSQLPairs = `${Path.ManagerAssist}/knowledge/question-sql-pairs`,
  KnowledgeInstructions = `${Path.ManagerAssist}/knowledge/instructions`,
  APIManagement = `${Path.ManagerAssist}/api-management`,
  APIManagementHistory = `${Path.ManagerAssist}/api-management/history`,
}
