export enum Path {
  ManagerAssist = '/managerAssist',
  Home = '/managerAssist/home',
  HomeDashboard = '/managerAssist/home/dashboard',
  Thread = '/managerAssist/home/[id]',
  Modeling = '/modeling',
  Onboarding = '/setup',
  OnboardingConnection = '/setup/connection',
  OnboardingModels = '/setup/models',
  OnboardingRelationships = '/setup/relationships',
  Knowledge = '/knowledge',
  KnowledgeQuestionSQLPairs = '/knowledge/question-sql-pairs',
  KnowledgeInstructions = '/knowledge/instructions',
  APIManagement = '/api-management',
  APIManagementHistory = '/api-management/history',
}
